name: ders
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  timezone: ^0.8.0
  cloud_firestore: ^3.1.12
  cupertino_icons: ^1.0.5
  firebase_storage: ^10.2.12
  flutter_slidable: ^1.2.0
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.0
  syncfusion_flutter_calendar: ^20.2.36
  flutter:
    sdk: flutter

dev_dependencies:
  get: ^4.6.1
  firebase_auth: ^3.3.13
  firebase_core: ^1.14.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1
  fluttertoast: ^8.0.9
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
